#! /bin/bash
#this script is created by Nile security (Abrham Arat(the da4k))

cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
blue='\e[1;34m'

echo ""
sleep 0.05
# Check root
[[ `id -u` -eq 0 ]] > /dev/null 2>&1 || { echo  $red "You must be root to run the script"; echo ; exit 1; }

clear

echo -e $green"===================================================================================================="
echo -e $yellow"=================================================================================================="
echo -e $red"===================================================================================================="
echo -e $green"================================================================================================="
                                        figlet -c Pass-word
echo -e $green"===================================================================================================="
echo -e $yellow"=================================================================================================="
echo -e $red"===================================================================================================="          
sleep 0.05         

# detect ctrl+c exiting
trap ctrl_c INT
ctrl_c() {
clear
echo -e $red"[*] (Ctrl + C ) Detected, Trying To Exit ..."
sleep 0.05
echo ""
echo -e $yellow"[*] Thanks for Nile SEC team  "
exit
}
 

echo -e $blue ""
echo ""
echo -e $cyan"    Create by           $white":" $red Nile Security Team @abrham_asrat"
echo -e $cyan"    Youtube Channel     $white":" $red https://www.youtube.com/@nilesecs"



 echo -e $cyan ""
 echo 
     echo -e $white"	[$okegreen"1"$white]$cyan Secure Password Generator "  
            sleep 0.05                    
    echo -e $white"	[$okegreen"2"$white]$cyan   Hide files on Image"
            sleep 0.05
    echo -e $white"	[$okegreen"3"$white]$cyan   Hash sam file"
            sleep 0.05
    echo -e $white"	[$okegreen"q"$white]$cyan QUIT "
   echo
        read -p "Select-->: " option
    echo

   case "$option" in 
    1) echo -e $red"Secure Pass Word Generator"
       
       python3 passGenerator.py
        echo ""
                             echo -e $red "##########  Pass-word ############"
                             echo
                             echo -e $green "【!】Return To The Main Menu【!】"
                             read -p "pess any key to return ..."
                     clear
       ;;
   2) echo -e $red"Hide Files ON Image" 
      sudo chmod +x steg
      sudo ./steg
       echo ""
                             echo -e $red "##########  Pass-word ############"
                             echo
                             echo -e $green "【!】Return To The Main Menu【!】"
                             read -p "pess any key to return ..."
                     clear
      ;;  
    3) echo -e $red "Hash Sam file"
       cd module
       sudo chmod +x hasher
       sudo ./hasher
          echo ""
                             echo -e $red "##########  Pass-word ############"
                             echo
                             echo -e $green "【!】Return To The Main Menu【!】"
                             read -p "pess any key to return ..."
                     clear
                     ;;
    q)  echo -e $yellow " Thanks For Using our Tools Good Bye  {Nile Sec}  !!"
                echo
                exit 0 
                ;;
    
        esac
 
