#!/bin/bash

set -e

cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
blue='\e[1;34m'



echo -e "Coice :
1-Encrypt
2-Decrypt "

read choice

      
if [[ $choice == 1 ]]; then
         
            echo -e $okgreen
            echo -e "====================================="
            read -p "Enter The File Path You Want To hide :" file
            echo -e "======================================"
             sleep 0.05
          echo -e "============================================"
          read -p "Enter The Imgae Path to HIde The above file:" image
          echo -e "============================================" 
              sudo steghide embed -cf  $image -ef $file
              rm $file
              mkdir /home/Documents/Hide
              mv $image /home/Documents/Hide

              echo -e $red
             echo -e "The File hass Beenn Encrypted!!"

            echo -e  "The File Is Found On /home/Documents/Hide :"
elif [[ $choice == 2 ]]; then
    echo -e $green
    echo -e "====================================="
        read -p "Enter The File Path TO unhide :" unhide
    echo -e "====================================="
     sudo steghide  extract  -sf  $unhide
     mv $unhide /home/Documents/Hide
     echo -e "The File IS found On /home/Documents/"
     echo -e "  "
         
else
     echo "The CHoice you enterd is invalid"

fi
                      echo
                             echo -e $green "【!】Return To The Main Menu【!】"
                             read -p "pess any key to return .."
               clear
