#!/bin/bash

cyan='\e[0;36m'
lightcyan='\e[96m'
green='\e[0;32m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
blue='\e[1;34m'


cd melkams
cd default

echo -e $green""
            
echo -e $green"===================================================================================================="
echo -e $yellow"=================================================================================================="
                                           figlet -c Melkam-cyber tool-Installer
echo -e $yellow"=================================================================================================="
echo -e $red"===================================================================================================="  
                       
   sleep 1                  
              
        
                    echo -e $blue ""
echo ""
echo -e $cyan"    Create by           $white":" $red Nile Security Team @abrham_asrat"
echo -e $cyan"    Youtube Channel     $white":" $red https://www.youtube.com/@nilesecs"
echo -e $lightgreen

sudo python3 installer
cd ..
cd ..
sudo chmod +x logo
sudo ./logo
cd melkams
echo -e $green""
echo -e "Installing required files..........."
sudo chmod +x requirement
sudo ./requirement
echo -e "The required Files install successfuly"
cd ..

	
 
sudo chmod +x  assets/icon/melkam.jpeg
echo -e $yellow"We start the Process.......... "
sudo cp -r melkams /usr/share/
echo -e $yellow"Wait a second......."
sudo cp -r melkams /usr/bin/
chmod +x  assets/icon/melkam.jpeg
	mkdir    /home/melkams/
	cp -r   assets/icon/melkam.jpeg /home/melkams/
	cp -r  /usr/share/melkam/assets/melkam.desktop  /home/melkams/
	cp -vr assets /usr/share/melkams
sudo cp -vr  /usr/share/melkams/assets/melkam.desktop /usr/share/kali-menu/applications/
sudo mv -v  /usr/share/melkams/assets/melkam.desktop /usr/share/applications/

sleep 2
#sudo make install
cp -r assets /usr/share/melkams
cp -r assets /usr/share/
cd /usr/bin

sudo chmod +x melkam




echo -e $green"USE this Tool For Ethical service !!"
sleep 2
echo -e $green"Be Patience almost The process Finished..................."
echo -e $green"Type $yellow melkam with root $green on the terminal"
echo -e $yellow"Thanks For My Mother(Melkam) and My full Family"


