#!/bin/bash

#This script is written by Abrham asrat(the da4k)
#this tools used to gain the most wanted infos in victim machine
set -e
 cd /usr/share/melkam
 
 sudo chmod +x ./abugida
 exec ./abugida
