#!/bin/bash
#This script is written by Abrham asrat(the da4k)
#this tools used to gain the most wanted infos in victim machine
set -e

clear




cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
blue='\e[1;34m'

Year=2015e.c
Codename=melkam

echo ""
sleep 0.5
# Check root
[[ `id -u` -eq 0 ]] > /dev/null 2>&1 || { echo -e $red"You must be root to run the script"; echo ; exit 1; }
echo -e $green"===================================================================================================="
echo -e $yellow"---------------------------------------------------------------------------------------------------"
echo -e $yellow"------------------------abrham---------------------------------------------------------------------"
echo -e $yellow"----------------------------from-Nile-sec-----------------------------------------------------------"
echo -e $yellow"---------------------------------------------------------------------------------------------------"

                                            figlet -c  From Nile Security
                                            sleep 0.5

echo -e $okegreen""
if [ $(id -u) != "0" ]; then

      echo [!]::[Check Dependencies] ;
      echo ""
   	  sleep 0.5
	  exit


else

   echo [!]::[Check Dependencies]: ;
   sleep 0.5
   echo [✔]::[Check User]: $USER ;

fi

sleep 0.5

# check nmap if exists
      which nmap > /dev/null 2>&1
      if [ "$?" -eq "0" ]; then
      echo [✔]::[nmap]: installation found!;
else

   echo [x]::[warning]:this script require Nmap ;
   echo ""
   echo [!]::[please wait]: please install .... ;
   apt-get update
   apt-get install nmap
   echo ""
   sleep 0.5
   exit
fi
sleep 0.5
# check urxvt if exists
      which figlet > /dev/null 2>&1
      if [ "$?" -eq "0" ]; then
      echo [✔]::[figlet]: installation found!;
else

   echo [x]::[warning]:this script require figlet;
   echo ""
   echo [!]::[please wait]: please install .... ;
   apt-get update
   apt-get install figlet
   echo ""
   sleep 0.5
   exit
fi
sleep 0.5
#lynis
      which lynis > /dev/null 2>&1
      if [ "$?" -eq "0" ]; then
      echo [✔]::[lynis]: installation found!;
else

   echo [x]::[warning]:this script require lynis;
   echo ""
   echo [!]::[please wait]: please install .... ;
   apt-get update
   apt-get install lynis
   echo ""
   sleep 0.5
   exit
fi
sleep 0.5
#python
      which python3 > /dev/null 2>&1
      if [ "$?" -eq "0" ]; then
      echo [✔]::[python3]: installation found!;
else

   echo [x]::[warning]:this script require python3;
   echo ""
   echo [!]::[please wait]: please install .... ;
   apt-get update
   apt-get install python3
   echo ""
   sleep 0.5
   exit
fi
sleep 0.5
#zenity 
 which zenity > /dev/null 2>&1
      if [ "$?" -eq "0" ]; then
      echo [✔]::[zenity]: installation found!;
else

   echo [x]::[warning]:this script require zenity;
   echo ""
   echo [!]::[please wait]: please install .... ;
   apt-get update
   apt-get install zenity
   echo ""
   sleep 0.5
   exit
fi
#msf
 which msfconsole > /dev/null 2>&1
      if [ "$?" -eq "0" ]; then
      echo [✔]::[Metasploit]: installation found!;
else

   echo [x]::[warning]:this script require Metasploit;
   echo ""
   echo [!]::[please wait]: please install .... ;
   apt-get update
   apt-get install msfconsole
   echo ""
   sleep 0.5
   exit
fi
# detect ctrl+c exiting
trap ctrl_c INT
ctrl_c() {
clear
echo -e $red"[*] (Ctrl + C ) Detected, Trying To Exit ..."
sleep 0.5
echo ""
echo -e $yellow"[*] Thanks for Nile SEC team  :)"
exit
}
clear


sleep 0.5

function main_menu() 
{
     while :
     do
     
     
echo "            ---Welcome to the world of Nilesec!---"
echo "           ---  from Nile cyber by Melkam team     ---."
echo "         ---       It was created on 2016 e.c       ----."
echo -e $okegreen ""
                figlet -f Varsity.flf -c Melkam
echo -e $blue ""
echo ""
echo -e $cyan"    Script by           $white":" $red Abrham Asrat ( Nilesec security ) "
echo -e $cyan"    Codename            $white":" $red $Codename "
echo -e $cyan"    Follow me on Github $white":" $red @nilesec "
echo -e $cyan"    Nile security       $white":" $red nilesec.blogpost.com "
echo -e $cyan"    Create by           $white":" $red NileSecurity Team "
echo -e $cyan"    Youtube Channel     $white":" $red https://www.youtube.com/@nilesecs"
echo -e $cyan"    Contrubuters        $white":" $red Hyle-maryam "
echo -e $cyan"                        $white"-" $red Efrem abi"
echo -e $cyan"                        $white"-" $red Senayt"
echo -e $cyan"    USER                $white":" $red Well come $(hostname -f 2> /dev/null)"
echo -e $cyan"    Os                  $white":" $red $(uname -a)"



        echo
        sleep 0.05
                       echo -e $white"	[$okegreen"1"$white]$cyan Computer " 
        sleep 0.05
                       echo -e $white"	[$okegreen"2"$white]$cyan Mobile  " 
        sleep 0.05
                       echo -e $white"	[$okegreen"3"$white]$cyan Other-hack  " 
                               sleep 0.05
                       echo -e $white"	[$okegreen"4"$white]$cyan see your default  " 
                       sleep 0.05
                       echo -e $white"	[$okegreen"5"$white]$cyan Services"  
        sleep 0.05       
        echo
                                       echo -n -e $red'  \033[4mmelkam@Nilesecs:\033[0m '; tput sgr0
        read option 

        case "$option" in 
          1) echo -e "Computer"
               sudo chmod +x melkam
               sudo ./melkam
               echo -e $red "##########  Computer ############"
                             echo
                             echo -e $green "【!】Return To The Main Menu【!】"
                             read -p "pess any key to return .."
               clear
               ;;
          2) echo -e "Mobile"

             sudo chmod +x mobiles
             sudo ./mobiles
             
             echo -e ""
             echo -e $red "##########  Mobile ############"
                             echo
                             echo -e $green "【!】Return To The Main Menu【!】"
                             read -p "pess any key to return .."

             clear
             ;;
          3) echo -e "Other Hacking"
              cd other
              sudo chmod +x other
              sudo ./other
              clear
              cd ..
              
              echo -e $red "##########  Other ############"
                             echo
                             echo -e $green "【!】Return To The Main Menu【!】"
                             read -p "pess any key to return .."
              clear
              ;;   
          4) echo -e "default"
             cd default
             clear
             sudo xterm -hold -fa monaco -fs 7 -bg black -e melkamcybers
             
             cd .. 
             ;;
          5) echo -e "services"
             clear
             cd service
             sudo python3 main.py
             cd ..
             ;;   
       esac   
    done
    
}
main_menu
