#!/bin/bash
# this script is developed by abugida security team Abrham Asrat(melkam)
#dont harm any one using this script

set -e

clear




#Colors
cyan='\e[0;36m'
lightcyan='\e[96m'
green='\e[0;32m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
blue='\e[1;34m'

os=android
format=apk

echo ""
sleep 0.05
# Check root
[[ `id -u` -eq 0 ]] > /dev/null 2>&1 || { echo  $red "You must be root to run the script"; echo ; exit 1; }

echo -e $green""
            
echo -e $green"===================================================================================================="
echo -e $yellow"=================================================================================================="
echo -e $red"===================================================================================================="
echo -e $green"================================================================================================="
                                        figlet -c Mobile-Malcious-app-Generator
echo -e $green"===================================================================================================="
echo -e $yellow"=================================================================================================="
echo -e $red"===================================================================================================="     
                       
                          
              
        
                    echo -e $blue ""
echo ""
echo -e $cyan"    Create by           $white":" $red Abugida Security Team @abrham_asrat"
echo -e $cyan"    Youtube Channel     $white":" $red https://www.youtube.com/c/Abugidasecurity"

 echo -e $cyan "    =====================                            ======================="
 echo -e $green"   ====================== list off aviliabile tools  =======================    ";
        echo
        sleep 0.05
        echo -e $white"	[$okegreen"1"$white]$cyan General-form" 
        sleep 0.05
        echo -e $white"	[$okegreen"2"$white]$cyan Inject-App " 
         sleep 0.05
       

        echo 
        echo -n -e $red'  \033[4mmelkam@Abugida:\033[0m '; tput sgr0
        read option 

        case "$option" in 
          1) echo -e "General(apk)"
               cd module
               sudo python3 general.py
               
                      echo
                             echo -e $green "【!】Return To The Main Menu【!】"
                             read -p "pess any key to return .."
               clear
               
               ;;
         2) echo -e "Inject-App"
 
              cd module
             sudo python3 inject
                                  echo
                             echo -e $green "【!】Return To The Main Menu【!】"
                             read -p "pess any key to return .."
               clear
             
           ;;
            
       esac           
