#!/bin/python3
import secrets


import os
import subprocess
from module.cl import color
import os
import random
import socket
import time
import subprocess
import platform
import datetime

os.system(
     f" sudo chmod +x banner && sudo ./banner"
 )
def generate_password(length):
  """Generates a random password of the specified length."""
  alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789~`!@#$%^&*()-_=+{}[]:;'<>,./?"
  password = ""
  for _ in range(length):
    password += secrets.choice(alphabet)
  return password

def main():
  """Prompts the user for the desired password length and generates a password."""
  length = int(input("How long do you want your password to be? (1-/no limt) : "))
  password = generate_password(length)
  print(f"Your password is Generated by Abugida Pass Generator : {password}")

if __name__ == "__main__":
  main()
