#!/bin/bash

#variables

cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
blue='\e[1;34m'

Year=2015e.c
Codename=theda4k



set -e

#clear the screen 
clear
echo -e $white
echo -e "#############################################################################################################"
echo -e "#            well come to melkam cyber lab(melkam.com)                                                      #"
echo -e "#                  from melkam Script By abrham asrat(abugida)                                              #"
echo -e "#            Created Date: 23/04/2016 e.c                                                                   #"
echo -e "#                    $red melkam Cyber lab                                                                      #" 
echo -e "#                                       $red Since $Year                                                      #" 
echo -e "#############################################################################################################\n"

echo -e $lightgreen
function ip_info()
{
    getip=$(zenity  --text=Enter-your-ip --entry=get-ip)
    

}
#the main function
function main()
{
      while :
      do
      
                       echo -e "[1]Get Info About Ip \n"
                       echo -e "[2]Get User name Of the computer \n"
                       echo -e "[3]Get The main \n"
                       
                       read -p"What is Your Prefered choice: " choice
                       
                       case $choice in
                       1)
                       ip_info
                       sudo nmap $getip
                       ;;
                       
     esac  
     done                
}
main

