#!/bin/bash
#This tool is written by abrham asrat{the da4k}
#this script is created by Nile security (Abrham Arat(the da4k))

set -e

clear




#Colors
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
blue='\e[1;34m'


echo ""
sleep 0.05
# Check root
[[ `id -u` -eq 0 ]] > /dev/null 2>&1 || { echo  $red "You must be root to run the script"; echo ; exit 1; }

echo -e $blue"---------------------------------------------------------------------------------------------------"
echo -e $blue"---------------------------------------------------------------------------------------------------"
echo -e $blue"---------------------------------------------------------------------------------------------------"
                        figlet -c Other-Hack
echo -e $yellow"-----------------------------------------------------------------------------------------" 
echo -e $yellow"------------------------------------------------------------------------------------------"           
sleep 0.05         

# detect ctrl+c exiting
trap ctrl_c INT
ctrl_c() {
clear
echo -e $red"[*] (Ctrl + C ) Detected, Trying To Exit ..."
sleep 0.05
echo ""
echo -e $yellow"[*] Thanks for Nile SEC team  "
exit
}
 

echo -e $blue ""
echo ""
echo -e $cyan"    Create by           $white":" $red Nile Security Team @abrham_asrat"
echo -e $cyan"    Youtube Channel     $white":" $red https://www.youtube.com/@nilesecs"

 echo -e $cyan "    =====================                            ======================="
 echo -e $green"   ====================== list off aviliabile tools  =======================    ";
 echo -e       "“If I had 6 h to chop down a tree, I’d spend the first four of them sharpening my axe.”"
        echo
        sleep 0.05
        echo -e $white"	[$okegreen"1"$white]$cyan abu-phish " 
        sleep 0.05
        
        echo -e $white"	[$okegreen"2"$white]$cyan Remote-control  " 
        sleep 0.05
        echo
        echo -n -e $red'  \033[4mmelkam@Nilesecs:\033[0m '; tput sgr0
        read option 

        case "$option" in 
          1) echo -e "Abuphish"
               cd abugida-phish
               sudo chmod +x abugida-phish
               sudo ./abugida-phish
                      echo
                             echo -e $green "【!】Return To The Main Menu【!】"
                             read -p "pess any key to return .."
               clear
              
               ;;
  
          2) echo -e "Remote-control"
              
              sudo chmod +x rde
              sudo ./rde
                                    echo
                             echo -e $green "【!】Return To The Main Menu【!】"
                             read -p "pess any key to return .."
               clear
            
              ;;       
       
       esac   
